TYPO3:
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          accessDeniedException:
            matchingExceptionClassNames: ['TYPO3\Flow\Security\Exception\AccessDeniedException', 'TYPO3\Flow\Security\Exception\NoTokensAuthenticatedException']
            options:
              templatePathAndFilename: 'resource://MOC.NotFound/Private/Templates/404.html'
              variables:
                path: 'accessdenied.html'
